inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
    - 'app/controllers/messages_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/notifications_helper.rb'
    - 'app/models/notification.rb'