version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  web:
    build: .
    image: web_singlecontainer
    volumes:
      - /app/log # persists log
    ports:
      - "80:80"
    depends_on:
      - db
      
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444
    tty: true
    stdin_open: true

volumes:
  gem_data:
