version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 4306:3306

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sharemusic
      - gem_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db 
      - chrome
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444
    tty: true
    stdin_open: true

volumes:
  gem_data:
